[phases.setup]
nixPkgs = ["python39", "python39Packages.pip"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt", "python3 -m playwright install chromium"]

[start]
cmd = "gunicorn main:app --bind 0.0.0.0:$PORT"
